---
title: Een nieuw Scratch-project maken
hero_image: afbeeldingen / banner.png
description: Maak een nieuw Scratch-project
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Maak een nieuw project
