---
title: Создание нового проекта Scratch
hero_image: images/banner.png
description: Создаeм новый проект Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Создаeм новый проект
