---
title: Oprettelse af et nyt Scratch-projekt
hero_image: images/banner.png
description: Opret et nyt Scratch-projekt
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Opret et nyt projekt
