---
title: Criar um projeto Scratch novo
hero_image: images/banner.png
description: Criar um projeto Scratch novo
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Criar um projeto novo
