---
title: Ang paglikha ng bagong proyekto sa Scratch
hero_image: images/banner.png
description: Lumilikha ng isang bagong proyekto sa Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - title: Lumikha ng isang bagong proyekto
