---
title: Ein neues Scratch-Projekt erstellen
hero_image: images/banner.png
description: Erstelle ein neues Scratch-Projekt
listed: false
ingredient: true
copyedit: true
steps:
  - title: Erstelle ein neues Projekt
