---
title: Crearea unui nou proiect Scratch
hero_image: images/banner.png
description: Creează un nou proiect Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Creează un nou proiect
