---
title: Criando um novo projeto Scratch
hero_image: images/banner.png
description: Crie um novo projeto Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - title: Crie um novo projeto
