---
title: Membuat sebuah proyek Scratch baru
hero_image: images/banner.png
description: Buat sebuah proyek Scratch baru
listed: false
ingredient: true
copyedit: true
steps:
  - title: Membuat sebuah proyek baru
