---
title: Creant un nou projecte de Scratch
hero_image: images/banner.png
description: Crea un projecte nou de Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Crea un projecte nou
