---
title: Ustvarjanje novega Scratch projekta
hero_image: images/banner.png
description: Ustvari nov Scratch projekt
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Ustvari nov projekt
