---
title: Új Scratch projekt létrehozása
hero_image: images/banner.png
description: Hozz létre egy új Scratch projektet
listed: false
ingredient: true
copyedit: true
steps:
  - title: Hozz létre egy új projektet
