---
title: Crear un nuevo proyecto Scratch
hero_image: images/banner.png
description: Crea un nuevo proyecto Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Crea un nuevo proyecto
