---
title: Tworzenie nowego projektu Scratch
hero_image: images/banner.png
description: Utwórz nowy projekt Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Utwórz nowy projekt
