---
title: Vytvorenie nového Scratch projektu
hero_image: images/banner.png
description: Vytvorte nový projekt v jazyku Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - title: Vytvorte nový projekt
