---
title: Skapa ett nytt Scratch-projekt
hero_image: images/banner.png
description: Skapa ett nytt Scratch-projekt
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Skapa ett nytt projekt
