---
title: Creating a new Scratch project
hero_image: images/banner.png
description: Create a new Scratch project
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Create a new project
