---
title: Créer un nouveau projet Scratch
hero_image: images/banner.png
description: Crée un nouveau projet Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Crée un nouveau projet
