---
title: Creare un nuovo progetto di Scratch
hero_image: images/banner.png
description: Creare un nuovo progetto di Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Crea un nuovo progetto
