---
title: Yeni bir Scratch projesi oluşturma
hero_image: images/banner.png
description: Yeni bir Scratch projesi oluşturun
listed: false
ingredient: true
copyedit: true
steps:
  - title: Yeni bir proje oluşturun
